name: Publish Helm

on:
  release:
    types: [published]

env:
  CHART_DIR: chart
  WORKFLOW_USER_NAME: ERP4SME-DevOps-GitHub-Workflow-User
  WORKFLOW_USER_EMAIL: 134080766+ERP4SME-DevOps-GitHub-Workflow-User@users.noreply.github.com

defaults:
  run:
    shell: bash

jobs:
  update-cop:
    runs-on: ubuntu-22.04
    env:
      COP_REPOSITORY: ${GITHUB_REPOSITORY/-2/-3}

    steps:
    - name: Process environment variables
      run: |
        echo "COP_REPOSITORY=$(eval echo $COP_REPOSITORY)" >> $GITHUB_ENV
        
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout component operator repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.COP_REPOSITORY }}
        path: cop-repository
        token: ${{ secrets.WORKFLOW_USER_GH_TOKEN }}

    - name: Update component operator repository
      run: |
        chart_name=$(yq .name $CHART_DIR/Chart.yaml)

        cd cop-repository
        old_version=$(yq .version pkg/operator/data/charts/$chart_name/Chart.yaml)
        new_version=${{ github.event.release.tag_name }}

        higher_version=$(echo -e "$old_version\n$new_version" | sort -r -n -t. -k1 -k2 -k3 | head -n1)
        if [ "$higher_version" != "$new_version" ]; then
          echo "Target version ($new_version) is lower than current version ($old_version); skipping update."
          exit 0
        fi

        echo "Updating chart (pkg/operator/data/charts/$chart_name) ..."
        rm -rf pkg/operator/data/charts/$chart_name
        cp -r ../$CHART_DIR pkg/operator/data/charts/$chart_name

        if [ -z "$(git status --porcelain)" ]; then
          echo "Nothing has changed; skipping update."
          exit 0
        fi

        git config user.name "$WORKFLOW_USER_NAME"
        git config user.email "$WORKFLOW_USER_EMAIL"
        git add -A
        git commit -F- <<END
        Update chart (triggered by operator helm release $new_version)
        Repository: ${{ github.repository }}
        Release: ${{ github.event.release.tag_name }}
        Commit: ${{ github.sha }}"
        END
        git push
